USE ROLE SYSADMIN;

CREATE FILE FORMAT IF NOT EXISTS DATA_PLATFORM.SOURCE.PARQUET_FILEFORMAT TYPE = PARQUET;
ALTER FILE FORMAT DATA_PLATFORM.SOURCE.PARQUET_FILEFORMAT SET
    TRIM_SPACE = FALSE
    NULL_IF = ()
    COMPRESSION = AUTO
    BINARY_AS_TEXT = TRUE
    REPLACE_INVALID_CHARACTERS = FALSE
    USE_LOGICAL_TYPE = FALSE;
