-- Set role to SYSADMIN
USE ROLE SYSADMIN;

-- Create SOURCE schema
CREATE SCHEMA IF NOT EXISTS DATA_PLATFORM.SOURCE;

-- Create STAGING schema
CREATE SCHEMA IF NOT EXISTS DATA_PLATFORM.STAGING;

-- Create TRANSFORM schema
CREATE SCHEMA IF NOT EXISTS DATA_PLATFORM.TRANSFORM;

-- Create FACT schema
CREATE SCHEMA IF NOT EXISTS DATA_PLATFORM.FACT;
