USE ROLE USERADMIN;

-- Create DBT_USER with SYSADMIN privileges
CREATE USER DBT_USER PASSWORD = 'j8KmP2qL9xR4vZ7nF';

-- Grant SYSADMIN role to DBT_USER
USE ROLE ACCOUNTADMIN;
GRANT ROLE SYSADMIN TO USER DBT_USER;

-- Set the default role for the user to SYSADMIN
ALTER USER DBT_USER SET DEFAULT_ROLE = SYSADMIN;
